// recipes.ts
import { Recipe } from "./types";

export const recipes: Recipe[] = [
  {
    id: 1,
    author: "Jim",
    name: "Chicken Curry",
    description: "Delicious spicy chicken curry.",
    ingredients: ["Chicken", "Curry powder", "Onions", "Garlic", "Ginger", "Tomatoes", "Coconut milk"],
    image: "/img/curry-chicken.jpg",
  },
  {
    id: 2,
    author: "Aravind",
    name: "Hamburger",
    description: "Juicy burger with toppings and a soft bun.",
    ingredients: ["Ground beef", "Buns", "Lettuce", "Tomato", "Cheese", "Pickles", "Onions", "Ketchup", "Mustard"],
    image: "/img/hamburger.jpg",
  },
  {
    id: 3,
    author: "Maria",
    name: "Pasta Carbonara",
    description: "Classic Italian pasta with creamy sauce.",
    ingredients: ["Spaghetti", "Eggs", "Parmesan cheese", "Pancetta", "Pepper", "Salt"],
    image: "/img/pasta-carbonara.jpg",
  },
  {
    id: 4,
    author: "Liu",
    name: "Sweet Pork",
    description: "Tangy and sweet pork dish.",
    ingredients: ["Pork", "Pineapple", "Bell peppers", "Onions", "Vinegar", "Sugar", "Soy sauce"],
    image: "/img/sweet-sour-pork.jpg",
  },
  {
    id: 5,
    author: "Alice",
    name: "Caesar Salad",
    description: "Crisp romaine lettuce with a creamy dressing.",
    ingredients: ["Romaine lettuce", "Caesar dressing", "Parmesan cheese", "Croutons", "Chicken (optional)"],
    image: "/img/caesar-salad.jpg",
  },
  {
    id: 6,
    author: "Yuki",
    name: "Sushi Rolls",
    description: "Assorted sushi rolls with fresh ingredients.",
    ingredients: ["Sushi rice", "Nori", "Fresh fish", "Cucumber", "Avocado", "Soy sauce", "Wasabi"],
    image: "/img/sushi-rolls.jpg",
  },
  {
    id: 7,
    author: "Carlos",
    name: "Tacos",
    description: "Tasty tacos with a variety of fillings.",
    ingredients: ["Tortillas", "Ground beef or chicken", "Lettuce", "Tomatoes", "Cheese", "Salsa", "Guacamole"],
    image: "/img/tacos.jpg",
  },
  {
    id: 8,
    author: "Eva",
    name: "Apple Pie",
    description: "Classic apple pie with a flaky crust.",
    ingredients: ["Apples", "Sugar", "Cinnamon", "Pie crust", "Butter"],
    image: "/img/apple-pie.jpg",
  },
  {
    id: 9,
    author: "Nina",
    name: "Greek Salad",
    description: "Fresh salad with feta cheese and olives.",
    ingredients: ["Cucumber", "Tomatoes", "Feta cheese", "Olives", "Red onion", "Olive oil", "Oregano"],
    image: "/img/greek-salad.jpg",
  },
  {
    id: 10,
    author: "Raj",
    name: "Butter Chicken",
    description: "Creamy and rich butter chicken.",
    ingredients: ["Chicken", "Butter", "Tomato sauce", "Cream", "Garlic", "Ginger", "Spices"],
    image: "/img/butter-chicken.jpg",
  },
  {
    id: 11,
    author: "Aisha",
    name: "Fried Veggies",
    description: "A quick and healthy stir-fry with a mix of colorful vegetables and a savory sauce.",
    ingredients: ["Broccoli", "Bell peppers", "Carrots", "Snap peas", "Soy sauce", "Garlic", "Ginger", "Sesame oil", "Green onions"],
    image: "/img/vegetable-stir-fry.jpg",
  },
  {
    id: 12,
    author: "Dave",
    name: "Brownies",
    description: "Rich and fudgy chocolate brownies with a chewy texture.",
    ingredients: ["Butter", "Sugar", "Cocoa powder", "Eggs", "Flour", "Vanilla extract", "Salt", "Chocolate chips"],
    image: "/img/chocolate-brownies.jpg",
  },
];
